### ISSUE TITLE
Working with pageContext

### ISSUE THREAD

**Issue by zzrez** [thriveweb/yellowcake#11]
How to include pageContext, to pass more data from gatsby-node.js to a page? For example, to the template BlogIndex.js. I tried various routes, including below:-

// Export Template for use in CMS preview
export const TourIndexPageTemplate = ({
  pageContext = [],
  title,.......etc

<Location>
    {({ location }) => {
      const { tag, place } = pageContext
      .......etc

const BlogIndex = ({ pageContext, data: { page, posts, postCategories } }) => (

but although this did not produce an error, neither the pageContext variables tag nor place passed any value.

**Comment by Firthir** [comment]
Hi @zzrez 
Can you provide a link to the full file?

**Comment by zzrez** [comment]
Thanks for fast answer, arriving at same time as machine being repaired here. Will reply shortly with details.

**Comment by zzrez** [comment]
Hi @Firthir 
The key files in repo https://github.com/zzrez/srezcake are:-
gatsby-node.js
src/templates/TourIndexPage.js

I am looking to see if your great yellowcake template can be modified for our use case (tours and activities). As https://srezcake.netlify.com/ shows, only change so far is adding sample tours for 2 regions (Jaco and Osa) in Costa Rica, treating them similarly to blog pages. Ie components and css files are copies of those for blog posts.

The major difference is that tours have more frontmatter fields, and tags (adventure, rainforest etc) vary for each region.

So lines 80-160 of gatsby-node.js create the various region/tag pages. Instead of using folders of md pages for regions and tour tags, arrays of tags for each region are created dynamically here. The problem is that context fields (line 140-4) pass data but attempts to get in the template page (TourIndexPage.js) have failed so far. This data is needed to filter the tours for each region/tag page, and to show the right tags for the region.

Current region/tag pages show all tours, not the correct filtered tours. For example, see these:-
https://srezcake.netlify.com/osa/adventure/
https://srezcake.netlify.com/jaco/combo/
https://srezcake.netlify.com/jaco/rainforest/

Grateful for advice on how to pass context. Thanks!

**Comment by zzrez** [comment]
Detailed question withdrawn. We used a different approach to solve this problem, which meant giving up with the yellowcake template which initially looked very promising. A pity.

**Comment by Firthir** [comment]
Cool thanks for the feedback.
