### ISSUE TITLE
How do I change the nav links?

### ISSUE THREAD

**Issue by drubio1989** [thriveweb/yellowcake#12]
This is my first time playing with Gatsby and Netlify, and I just can't for the life of me get the nav links to change with this template. Where am I supposed to edit the nav links? I've tried to play around with config.yml and gatsby-node.js but I still am unable to get the nav links to change. 

For example, I can't change the link "Component" to "Courses". Can someone please give me a small example to move along. It would be greatly appreciated.

**Comment by Firthir** [comment]
Yeah, this is a good question. It takes a minute to get your head around.
First make a new file in /content/pages/courses.md
`template: CoursesPage
slug: courses
title: Our Courses`

Then edit the /components/Layouts.js file.
`<NavLink to="/courses/">Our courses</NavLink>`

That a good start. then create a page template and pull the conent from the .md file through the graphql and spit it out with jsx.
