### ISSUE TITLE
CMS not passing Class Names on custom pages

### ISSUE THREAD

**Issue by flamebeard** [thriveweb/yellowcake#14]
There is a reference to a ```styles.css``` in ```cms.js``` however I cannot find that file ```styles.css```. I'm picking this why the styling isn't working in the Preview Pages when you're editing in the backend of the CMS

**Comment by Firthir** [comment]
Yes, cleaning a few things up with style. I'll have to check up on this later on.

**Comment by flamebeard** [comment]
More on this. Its not that ```styles.css``` isn't being loaded. Its that in the CMS. Some pages don't get the correct class names added. For example. Home Page see below. 

![image](https://user-images.githubusercontent.com/23321960/70190172-f0971380-1740-11ea-8a37-555705aa4bbf.png)

Then we see a custom page that has been added. 
![image](https://user-images.githubusercontent.com/23321960/70190208-01478980-1741-11ea-8c18-08d1972d7ab1.png)

we get these weird pseudo class names.

**Comment by Firthir** [comment]
Ok, you need to apply a template to your new services page. Then for the CMS preview panel to work look at the cms.js follow the pattern.  

`import { DefaultPageTemplate } from '../templates/DefaultPage'`
Then
`CMS.registerPreviewTemplate('infoPages', ({ entry }) => (
  <DefaultPageTemplate {...entry.toJS().data} />
))`

Let me know how you go :)

**Comment by Firthir** [comment]
As far as the reference to styles this loads the built public version of your css so the preview panel looks like the live site.
`if (
  window.location.hostname === 'localhost' &&
  window.localStorage.getItem('netlifySiteURL')
) {
  CMS.registerPreviewStyle(
    window.localStorage.getItem('netlifySiteURL') + '/styles.css'
  )
} else {
  CMS.registerPreviewStyle('/styles.css')
}`

**Comment by flamebeard** [comment]
Alright. That makes a lot more sense. I've added in the templates to CMS.js however I'm still getting some weird stuff happening here. 

For reference the repo is here. https://github.com/flamebeard/WhereAmI

> As far as the reference to styles this loads the built public version of your css so the preview panel looks like the live site.
```if ( window.location.hostname === 'localhost' && window.localStorage.getItem('netlifySiteURL') ) { CMS.registerPreviewStyle( window.localStorage.getItem('netlifySiteURL') + '/styles.css' ) } else { CMS.registerPreviewStyle('/styles.css') }```

Where is the above code? I couldn't find that in the repo? 

Thanks for your help too!

**Comment by Firthir** [comment]
Have you got it up on Netlify? enable identity and all that jazz. shouldn't need to change this but is on the top of this page :) https://github.com/thriveweb/yellowcake/blob/master/src/cms/cms.js

**Comment by flamebeard** [comment]
Just worked this out. Under ```cms.js``` I had forgot to register the name of the page from ```config.yml```

for example it looked like this 

```
CMS.registerPreviewTemplate('blog', ({ entry }) => (
  <HowPageTemplate {...entry.toJS().data} />
))
```

When it should have looked like this 

```
CMS.registerPreviewTemplate('how-page', ({ entry }) => (
  <HowPageTemplate {...entry.toJS().data} />
))
```

**Comment by flamebeard** [comment]
Thank you for your help mate!
