### ISSUE TITLE
RangeError: Invalid time value

### ISSUE THREAD

**Issue by doakheggeness** [thriveweb/yellowcake#22]
I updated the package.json file per `ncu -u`.  I got the following error when displaying single posts.
In the package.json file, I also upgraded `npm-css` to `npm-css-app`.

![package-json](https://user-images.githubusercontent.com/1179369/67884626-65a07900-fb03-11e9-849b-8e064e68a125.jpg)
![upgrade-error](https://user-images.githubusercontent.com/1179369/67884636-689b6980-fb03-11e9-91fa-b07d77663666.jpg)

This is over my head as I am a nooby. I really like your starter.
Thanks

**Comment by doakheggeness** [comment]
I modified SinglePost.js......

I added formatting to the `date` in Graphql `date(formatString: "MMMM, DD, YYYY") and removed the date formatting on line 36 to `{date}`. I do miss the `th` in the day though. Gatsby uses Moment.js for this.

I could not get `date-fns` v2.60 to work.

**Comment by Firthir** [comment]
Good upgrade could you make a pull request? Moment.js is a better solution. Thanks for the info @doakheggeness :)

**Comment by Firthir** [comment]
Thanks for the pull request :)
