### ISSUE TITLE
Will the third party aspects of this project (netlify cms, mailchimp, uploadcare, etc) work if I copy the repo to bitbucket?

### ISSUE THREAD

**Issue by jajourda** [thriveweb/yellowcake#26]
The title says it all, but repetition for clarity:

Will the third party aspects of this project (netlify cms, mailchimp, uploadcare, etc) work/be supported if I copy the repo to bitbucket?

**Comment by Firthir** [comment]
Yes, is the short answer :) Mailchimp & Uploadcare need to set up correctly. It's really all about the netlify support of bit bucket I've not tested. Github was the first and is just so easy.

**Comment by jajourda** [comment]
Is there a way to set the git repository to private without a paid account?
Free private repositories are the only draw for me regarding bitbucket on
this particular project.

**Comment by Firthir** [comment]
I've tested Gitlab and would say the netlify team have sorted bitbucket. No way for free private on git hub.

**Comment by brunetsimon** [comment]
There are such things as free github private repo. Works perfectly with this setup.
https://github.blog/2019-01-07-new-year-new-github/

**Comment by jajourda** [comment]
You guys rock! Thanks for quick responses, and that is great news! Happy New Year.
