### ISSUE TITLE
Email not confirmed / Email links not working

### ISSUE THREAD

**Issue by MatthewTrout** [thriveweb/yellowcake#27]
I've deployed this into my netlify using the one click route, all works fine and all settings in app have been already configured as per instructions in readme.  However I can't login to the admin.  Any link that is emailed (signup / password reset), takes me to the homepage and doesn't progress.  Around the internet people say this is something to do with the identity widget not being on the homepage? But I'd expect it is given that that this starter is configured for netlify specifically?  Apologies if I'm missing something obvious!

**Comment by Firthir** [comment]
Hi @MatthewTrout 
Glade you are spinning repo this up :) It works out the box. Try hardcode a change to the /content/pages/home.md say change the title & commit to your repo, to test that is all working.
Then check Netlify deploy. If that is all working then it's got to be the identity settings. 
Check your invited user list in Netlify admin identity top menu
Delete and reset Netlify’s Git Gateway under setting identity
Let me know how you go.

**Comment by MatthewTrout** [comment]
Hi there, thanks for responding. I tried all of the above to no avail. However when I set up a custom domain for the Netlify app instance, then resent a password reset email that seemed to work fine..!

**Comment by maxehnert** [comment]
@Firthir I wanted to comment and say I was experiencing the same issue as the OP. Generating a new github api access token resolved the issue in my case.
