### ISSUE TITLE
Copyright removable?

### ISSUE THREAD

**Issue by xstable** [thriveweb/yellowcake#31]
Does your starter kit has an license?
Can I remove the copyright on the very bottom of the page?

**Comment by Firthir** [comment]
We are using the standard MIT License
Copyright (c) Thrive Digital Pty Ltd can be removed from the footer to create your website :)
Shoot me a link of what you create if you want.

**Comment by xstable** [comment]
@Firthir thanks. Even for sharing your template under MIT.
Currently I start with my first steps on Gatsby and Netlify-CMS, but it will get more soon.

First I port my Webpage erfolgsbeginn.de to it. I will see if I can generate Pull-Requests if I add or optimize something... to contribute and honor your work.
