### ISSUE TITLE
Flickr integration as Image-Gallery

### ISSUE THREAD

**Issue by xstable** [thriveweb/yellowcake#39]
We still have Instagramm-Feed integration in yellowcake.
I think it would be nice to also integrate Flickr as service for Image-Galleries.

Flickr is a bit different from Instagramm. While the main purpose of Instagramms is to show a Feed of (newest) images, Flickr's main purpose is to generate Albums which should be accessible for a long time.

There is still an [Gatsby-Plugin](https://www.gatsbyjs.org/packages/gatsby-source-flickr/?=flickr) for that. Would love to see an nice implementation for yellowcake with it.

**Comment by Firthir** [comment]
Thanks for the input. Would you like to make a pull request :)
