### ISSUE TITLE
contact form entries not saved in netlify forms

### ISSUE THREAD

**Issue by ecomloop** [thriveweb/yellowcake#44]
Form entries appear to be working from front end - but are not being saved in Netlify Forms. 

This is my first attempt at implementing netlify forms. I have updated API for repcatcha and see form name in Netlify forms. I've submitted multiple entries and none are captures. 

What settings should I check/update?

**Comment by jrvscm** [comment]
same ⬆️

**Comment by Firthir** [comment]
I assume you have been through the docs. What testing have you guys tried and how did it fail?
https://docs.netlify.com/forms/submissions/#form-submissions-ui

**Comment by jrvscm** [comment]
I have been through the docs. But still seems like something is up. I am new to Netlify forms so I could most certainly be doing something wrong.

Basically I fill out the form, submit with data, and it shows me the success message. But I never see the form submission show up in the Netlify dashboard. I see the post in the network tab with all my dad in the headers.

I saw that on the gender checkbox input the names are the same, so I tried changing it to gender-male, gender-female, to be sure that they were different. But still did not see any submissions in spam or verified.

Seems like the form is set up the way the docs describe but something isn't connecting up. I can see the form, in the admin panel with the name but still no submissions.

Also tried adding honeypot field but still nothing. Any Ideas @Firthir? Thanks for the reply.

**Comment by Firthir** [comment]
Hey @jrvscm  try making a new from directly from the example and let me know how it goes.
https://docs.netlify.com/forms/setup/#html-forms

**Comment by jrvscm** [comment]
@Firthir was an error on my part. Had the wrong keys in my netlify admin. Thanks for the great starter!

**Comment by Firthir** [comment]
Thanks @jrvscm
