### ISSUE TITLE
Images blurred out on Google Pixel 3

### ISSUE THREAD

**Issue by joebram** [thriveweb/yellowcake#45]
The images across the site seem to be blurred out when viewing on a Google Pixel 3 with Android and Chrome. Seems fine on an iPhone.
![Screenshot_20200422-142826](https://user-images.githubusercontent.com/38935606/79988117-2f3a2a00-84a6-11ea-8c98-3118e9d4f344.png)
![Screenshot_20200422-142926](https://user-images.githubusercontent.com/38935606/79988121-306b5700-84a6-11ea-99cb-930958217dd6.png)

**Comment by Firthir** [comment]
Thanks for the update. The intersection observer is not working. I don't have access to this device type for the test yet. Could you visit this Codepen and let me know if you're still having the issue.
https://codepen.io/afrith/pen/BaopQgY

**Comment by joebram** [comment]
Thanks, I get a rectangle saying 'observed'. Screenshot attached.
![Screenshot_20200423-065430](https://user-images.githubusercontent.com/38935606/80064271-9819b480-852f-11ea-9655-d9bc8622849d.png)

**Comment by Firthir** [comment]
I hope to get time to look into this later. For now working on the start you disable lazy images with lazy option/prop with the images component. See https://github.com/thriveweb/yellowcake/blob/master/src/components/Image.js

**Comment by joebram** [comment]
Thanks, so I changed the lazyload value to false and now the images don't load in desktop either, am I changing the right settings?

**Comment by Firthir** [comment]
Cool, you found a bug. I've updated the repo and here is the code, or you can pull it in :). 

```let style = {}
    if (background && lazy) {
      style = {
        backgroundImage: `url(${
          this.state.isIntersecting ? fullSrc : smallSrc
        })`,
        backgroundSize
      }
    } else {
      style = {
        backgroundImage: `url(${fullSrc})`,
        backgroundSize
      }
    } 

https://github.com/thriveweb/yellowcake/blob/master/src/components/Image.js

```
Then add lazy={false} to the image you want.  
Example use: https://github.com/thriveweb/yellowcake/blob/master/src/components/PageHeader.js. 
```
if (large) className += ' PageHeader-large'
  return (
    <div className={`PageHeader relative ${className}`}>
      {backgroundImage && (
        <Image
          background
          resolutions="large"
          src={backgroundImage}
          alt={title}
          size="cover"
          lazy={false}
        />
      )}
```

**Comment by joebram** [comment]
Cool, glad it's been of some use! This might sound daft but I'd like to try and pull it in, bit of a novice with github, is it hard to do?

**Comment by joebram** [comment]
Hey, the images load in incognito using chrome but not in the normal browser page, have cleared the cache etc...

Also, on a different subject is there any documentation about adding another page using specific components?

Thanks,
Joe

**Comment by Firthir** [comment]
Gatsby has an application cache. @joebram you can find this in chrome inspect element > Application tab at the top > Cache on the left-hand menu > cache storage. 
Delete that and you should be sorted.

**Comment by belamrani** [comment]
Hello @Firthir . I have the same problem on a OnePlus 6. Have you found a better solution than disable the lazy loading ? 

Thank you !
