### ISSUE TITLE
how can i remove the github top right corner in CMS?

### ISSUE THREAD

**Issue by fdq09eca** [thriveweb/yellowcake#51]
Firstly, Thank you for this wonderful template. I am not a Gatsby user. I choose this theme totally because of its complete CMS, and the readily deploy uploading and contact form feature. Is there a way to remove the top right corner GitHub repo link?
![image](https://user-images.githubusercontent.com/51902242/86321135-f9b27980-bc6a-11ea-8834-ed741830b1fc.png)

**Comment by Firthir** [comment]
Hey @fdq09eca you just need to make some code edits.
Look for Github corner in this file and remove it https://github.com/thriveweb/yellowcake/blob/master/src/components/Layout.js

**Comment by fdq09eca** [comment]
@Firthir thanks, I am new to react too :)
