### ISSUE TITLE
How to change slugs for posts and pages?

### ISSUE THREAD

**Issue by austinaccidentlawyer** [thriveweb/yellowcake#56]
I want to set the posts slug as **"https://domain.com/blog/category-name/post-name"** and sub-page slug as  **"https://domain.com/info-page/page-name"** Also how should I create sub-menu for pages e.g. "Info Page -> Default" similar to "Blog->News/Updates"

Please advise how to achieve it with this template.

**Comment by emmadigital** [comment]
Any update on this query

**Comment by Firthir** [comment]
The file you need to look into is, there are comments explaining how slugs work.
- https://github.com/thriveweb/yellowcake/blob/master/gatsby-node.js
