### ISSUE TITLE
Featured Image not displaying

### ISSUE THREAD

**Issue by emmadigital** [thriveweb/yellowcake#61]
I am fetching blog images from "static/images" folder rather than uploadcare but it does not loads featured image. Can you suggest solution.

![image](https://user-images.githubusercontent.com/64609778/91724733-6af8a500-eba6-11ea-908c-ad60f16b8351.png)

**gatsby-config.js**
```
    {
      resolve: 'gatsby-source-filesystem',
      options: {
        path: `${__dirname}/static/images`,
        name: 'images'
      }
    },
```

**Config.yml**
```
media_folder: static/images
public_folder: /images
```

**On Markdown File**
![image](https://user-images.githubusercontent.com/64609778/91724325-d0986180-eba5-11ea-9ce9-0cedb52aa939.png)

**On Graphql** 
![image](https://user-images.githubusercontent.com/64609778/91724373-e73eb880-eba5-11ea-9e82-750ba577257b.png)

How should I save the exact featuredImage path to graphql which is in markdown file. Do I need to make path changes in gatsby-config.js or config.yml file? Please advise.

**Comment by Firthir** [comment]
That is not a straight forward switch. This file is all about images and how it's handled.
https://github.com/thriveweb/yellowcake/blob/master/src/components/Image.js
