### ISSUE TITLE
Form submission and Google map not working

### ISSUE THREAD

**Issue by emmadigital** [thriveweb/yellowcake#67]
The form show up on Netlify Forms section but when I submit a form it gets submitted but submissions are empty for both FormSimple and FormSimpleAjax. Please explain how the form works in your theme. 

I have tested form by creating a simple form (named referrals) as instructed here https://docs.netlify.com/forms/setup/#html-forms and submissions are working with this form as shown in below screenshot.

![image](https://user-images.githubusercontent.com/64609778/92710922-db4eb580-f360-11ea-8daf-bddaab9573db.png)

Google Map shows For development purpose only, how can I make it work normaly
![image](https://user-images.githubusercontent.com/64609778/92710588-99257400-f360-11ea-9041-049d5fce9715.png)

**Comment by Firthir** [comment]
Try to make your own form following the docs then you will better understand how the forms work.
Google map requires an API key.
Add it manually for testing after that I recommend using environment variables.
https://github.com/thriveweb/yellowcake/blob/master/src/components/GoogleMap.js
let mapkey = ''
if (process.env.NETLIFY_MAP_KEY) {
  mapkey = process.env.NETLIFY_MAP_KEY
}
