### ISSUE TITLE
Graphql Query Error for featuredImages

### ISSUE THREAD

**Issue by emmadigital** [thriveweb/yellowcake#69]
**Summary**
I get graphql query error for featuredImage field, sometime it works fine but sometimes I get below error but when I run gatsby clean command 3 - 4 times the error goes away. I want to know the permanent solution to this.

**Relevant information**
Here is the screenshot of the error and my graphql query for fetching featuredImage:

![image](https://user-images.githubusercontent.com/64609778/93974549-a2f6a080-fd7e-11ea-86d7-422c425e87d4.png)

**Graphql Query for ContactPage**
```
export const pageQuery = graphql`
  query ContactPage($id: String!) {
    page: markdownRemark(id: { eq: $id }) {
      ...Meta
      html
      frontmatter {
        title
        template
        subtitle
        featuredImage
        address
        phone
        email
        locations {
          mapLink
          lat
          lng
        }
      }
    }
  }
`
```
**PageHeader Component**
 ```
  <PageHeader
      title={title}
      subtitle={subtitle}
      backgroundImage={featuredImage}
    />
```
**Image Component**
```
        <Image
          background
          resolutions="large"
          src={ImageHeader}
          alt={title}
          size="cover"
        />
```

Screenshot of GraphiQL

![image](https://user-images.githubusercontent.com/64609778/93974761-fa950c00-fd7e-11ea-8903-434f1a9650fd.png)

Either there is a issue with graphlq or above components.
My Netlify build sometime also fails because of this featuredImage issue. Please advise whats the permanent solution for this problem.

And there is no publicURL showing up in graphiql for featured images which I can use instead.

Normally I use below structure for fetching featured images but this template doesn't have subfields for featured image field because of this it throws error most of the time. I would really appreciate if you can provide a reliable solution for fetching images.

```
 featuredImage {
              childImageSharp {
                fluid(maxWidth: 1200, quality: 64) {
                  ...GatsbyImageSharpFluid
                  src
                }
              }
            }
```

**Comment by emmadigital** [comment]
Is this issue because of the old version of `gatsby-remark-relative-images` plugin, as here the latest version which is different https://www.npmjs.com/package/gatsby-remark-relative-images

**Comment by Firthir** [comment]
ok thanks
