### ISSUE TITLE
Google Map dynamic values

### ISSUE THREAD

**Issue by emmadigital** [thriveweb/yellowcake#70]
Google map is not fetching values that we are passing from ContactPage template
https://github.com/thriveweb/yellowcake/blob/d35c8b2785599774b66b98cee8c7b1c26990f20e/src/templates/ContactPage.js#L65

`<GoogleMap locations={locations} />`

Its using some default props. How should I make it work for values we are passing with above code.
https://github.com/thriveweb/yellowcake/blob/d35c8b2785599774b66b98cee8c7b1c26990f20e/src/components/GoogleMap.js#L11

If I try to set locations value that is passed from ContactPage:   `defaultCenter={locations}` It say the default props can not be changed.

```
import React, { Component } from 'react'
import GoogleMapReact from 'google-map-react'
import { MapPin } from 'react-feather'

let mapkey = ''
mapkey = 'xxxxxxxxxxxxxxxxxxxxxxxxx'

class GoogleMap extends Component {
  static defaultProps = {
    center: {
      lat: 30.373000,
      lng: -97.736600
    },
    zoom: 14.7
  }

  render() {
    const { locations } = this.props

    return (
      // Important! Always set the container height explicitly
      <div style={{ height: '50vh', width: '100%' }}>
        <GoogleMapReact
          bootstrapURLKeys={{ key: mapkey }}
          defaultCenter={locations}
          defaultZoom={this.props.zoom}
        >
          <Marker lat={30.373000} lng={-97.736600} text={'Complete Address'} />
        </GoogleMapReact>
      </div>
    )
  }
}

export default GoogleMap

const Marker = () => {
  return (
    <div style={{ color: 'red' }}>
      <MapPin />
    </div>
  )
}

```

**Comment by Firthir** [comment]
This starter theme does not have that feature. 
If you create one, make a pull request.
:)
