### ISSUE TITLE
Re-work the click events 

### ISSUE THREAD

**Issue by Firthir** [thriveweb/yellowcake#72]
A Hacktoberfest pull request help wanted.  
It would be great if someone could help with add all the eslinter requirements the non-native to click events like DIV's.
See all files marked with linter warnings for clickable elements remove this and you will see the warnings.
Thanks @abhijit-hota I've updated this request.

Following this example:
`onKeyDown={this.handleKeyDown}
            tabIndex={0}
            aria-label="Toggle Popup"
            role="button"`

**Comment by Firthir** [comment]
If you are interested in helping I've started with the Popup.js on this branch.
https://github.com/thriveweb/yellowcake/tree/Popuplinter

**Comment by abhijit-hota** [comment]
What about the styling of the divs when replaced by say, buttons?

**Comment by Firthir** [comment]
@abhijit-hota I've updated this request to make better changes :)

**Comment by abhijit-hota** [comment]
I'll take this.

**Comment by Firthir** [comment]
These have been resolved now. Es linter is back and up and running on all components.
