### ISSUE TITLE
CMS access stopped after changing repo to private

### ISSUE THREAD

**Issue by zzrez** [thriveweb/yellowcake#9]
Really liked the blog demo, and the easy setup of NetlifyCMS along with hosting. But when I changed the cloned repo to private, CMS access stopped. That is, on clicking the "Login with Netlify Identity" button, a yellow notification appeared above saying "Not found". How to correct?

[On putting the cloned repo back to public, access to NetlifyCMS was restored. But desirable to make repo private if to be customised]

**Comment by zzrez** [comment]
Sorry just found solution was to re-issue token, as indicated in https://www.netlify.com/docs/git-gateway/#getting-started

**Comment by Firthir** [comment]
thanks for the update @zzrez :)

**Comment by howchurchworks** [comment]
i'm trying to sort through this issue right now. wating on the https to propagate... #
