### ISSUE TITLE
Netlify CMS - Uploadcare Missing External Library

### ISSUE THREAD

**Issue by mont266** [thriveweb/yellowcake#91]
My website deploys correctly but whenever I try to access my Netlify CMS admin panel I get this error:
Error loading the CMS configuration

Config Errors:

Error: Missing external media library ‘uploadcare’. Please use ‘registerMediaLibrary’ to register it.

Check your config.yml file.

Here is my config.yml file: https://pastebin.com/raw/gHzhvTGG

Here is my cms.js file: https://pastebin.com/raw/wMGtkKwm

Uploadcare has been registered and it has a valid api key. It was working fine previously.

I am running out of things to try

**Comment by Klrfl** [comment]
How did you solve it?
